### ISSUE TITLE
Issue showing active store name in store switcher or dashboard

### ISSUE THREAD

**Issue by thetalesofj** [AntonioErdeljac/next13-ecommerce-admin#11]
I have been following the tutorial closely whilst learning Prisma and MySQL. I have come across an issue with the store name not showing in the store switcher when selected. In addition, the active store name will not change on the dashboard page and thus the store id is `undefined` in the settings section.

Here is a link to my [repo](https://github.com/thetalesofj/cms-admin-for-next.js-stores). From what I can tell from the tutorial video and code on here, I haven't made any noticeable mistakes.

Any help would be appreciated!

**Comment by AhmedAlsudairy** [comment]
me too same issue

**Comment by AhmedAlsudairy** [comment]
check your path name file it is [storeid] not [storeId] you mispelled pathname file ,useParams method got id from url and there is no pathname called storeId in file router

**Comment by thetalesofj** [comment]
> check your path name file it is [storeid] not [storeId] you misspelled pathname file ,useParams method got id from url and there is no pathname called storeId in file router

Sigh, it's always the simple mistakes that have you scracting your head. Thank you!
