### ISSUE TITLE
Warning: Only plain objects can be passed to Client Components from Server Components. Decimal objects are not supported.

### ISSUE THREAD

**Issue by Op-Pautu** [AntonioErdeljac/next13-ecommerce-admin#20]
In (routes)->products->page.tsx, i wrote like adrian: 
 price: formatter.format(item.price.toNumber())
 
 but i get this error

**Comment by EadwineZhao** [comment]
The issue at hand isn't related to this code. It should be located in the `[productId].page.tsx` file. 

The `product` object contains a `price` property of type `Decimal`, and it's essential to parse it before passing it to client.

**Comment by Op-Pautu** [comment]
that file goes like this no?

`import prismadb from "@/lib/prismadb";

import { ProductForm } from "./components/ProductForm";

const ProductPage = async ({
  params,
}: {
  params: { productId: string; storeId: string };
}) => {
  const product = await prismadb.product.findUnique({
    where: {
      id: params.productId,
    },
    include: {
      images: true,
    },
  });

  const categories = await prismadb.category.findMany({
    where: {
      storeId: params.storeId,
    },
  });

  const sizes = await prismadb.size.findMany({
    where: {
      storeId: params.storeId,
    },
  });

  const colors = await prismadb.color.findMany({
    where: {
      storeId: params.storeId,
    },
  });

  return (
    <div className="flex-col">
      <div className="flex-1 space-y-4 p-8 pt-6">
        <ProductForm
          categories={categories}
          colors={colors}
          sizes={sizes}
          initialData={product}
        />
      </div>
    </div>
  );
};
`

**Comment by EadwineZhao** [comment]
**product-form.tsx**

// add export ,this type is used on products/page.tsx page
export type ProductFormValues = z.infer<typeof formSchema>;

// change initialData type 
interface ProductFormProps {
  initialData: ProductFormValues | null;
  categories: Category[];
  colors: Color[];
  sizes: Size[];
}


 **products/page.tsx** 
//format product object

  let formatedProduct: ProductFormValues | null = null;

  if (product) {
    formatedProduct = {
      ...product,
      price: parseFloat(product?.price.toString()),
    };
  }

//change initialData to be formatedProduct
<ProductForm
          initialData={formatedProduct}
          categories={categories}
          sizes={sizes}
          colors={colors}
        />

These changes ensure that the `ProductForm` components receives the properly formatted initial data for rendering.
