### ISSUE TITLE
Error: Invalid `prisma.billboard.findUnique()` invocation:

### ISSUE THREAD

**Issue by ProtheanEngineer** [AntonioErdeljac/next13-ecommerce-admin#22]
Whenever I try to add a new Billboard, I get the error Invalid `prisma.billboard.findUnique()` invocation:
Inconsistent column data: Malformed ObjectID: provided hex string representation must be exactly 12 bytes, instead got: "new", length 3.

That's because in the billboards's component "client.tsx", when the "Add New" button's is clicked, the navigate to the {params.storeId}/billboards/new` route. 

But, in the billboards/[billboardId] page.tsx, when we define the const "billboard" we can't find that FindUnique where id: params.billboardId.

I'm looking around but can't figure out how to solve that.

Thanks in advance!

**Comment by DANY-DURAND** [comment]
Same issue here. Did you find any solution for it?

**Comment by NgatiaJeffers** [comment]
I had the same issue as I'm using MongoDB to store my data, apparently MongoDB, in my case, expects a 12-byte ObjectID but it gets a string on length 3.

**Solution:**
On the utils file I created a generate12ByteId() function to help in generating a new 12-byte for the param, here is my function 

```
export function generate12ByteId(byteLength: any) {
// Check for crypto support.**
  if (typeof crypto === 'undefined' || !crypto.getRandomValues) {
    throw new Error('Crypto support not found. Unable to generate secure ID.');
    }

// Generate random bytes based on the specified byteLength.
   const randomBytes = new Uint8Array(byteLength);
   crypto.getRandomValues(randomBytes);

 // Convert the random bytes to a hexadecimal string.
  const hexString = Array.from(randomBytes).map(byte => byte.toString(16).padStart(2, '0')).join('');

  // Return the hexadecimal string as the ID.
   return hexString;
 }
```

Then the second part of the code change is to update how you get your unique ID for instance on the **Page.tsx** file under **[billboardID]** folder, this is how I use the function to generate a 12-byte ID for every new billboard creation

```
    // Check billboard ID on params
    const checkParamIdForBillboard = (params: any) => {
        if (params?.billboardId === "new") {
            const id = generate12ByteId(12);
            return id;
        }
        return params?.billboard;
    }

    const billboard = await prismadb.billboard.findUnique({
        where: {
            id: checkParamIdForBillboard(params)
        }
    });
```

@DANY-DURAND  @ProtheanEngineer  hopefully this helps or gives an idea to solve your problem

**Comment by ProtheanEngineer** [comment]
Thanks a lot, @NgatiaJeffers!

I'm new using MongoDB and your message helped me a lot.

I used the code you provided and it works fine.

**Comment by DANY-DURAND** [comment]
Thanks, @NgatiaJeffers!
