### ISSUE TITLE
Create store option on the store switcher is not working

### ISSUE THREAD

**Issue by masterthuku** [AntonioErdeljac/next13-ecommerce-admin#35]
I'm in the first stage of coding the app after I have finished the store-switcher and running the program, the create store option is not working and there are no error messages. checked the hooks, use store modal and the store switcher and I cant find the error. Please help
here is my code so far. https://github.com/masterthuku/e-commerce-admin

**Comment by NickCoder123** [comment]
I have the same error man! Did you fix it?
