### ISSUE TITLE
Login Dashboard Error: Unable to Access the Dashboard

### ISSUE THREAD

**Issue by neeravbhaskarla** [AntonioErdeljac/next13-ecommerce-admin#4]
<img width="760" alt="image" src="https://github.com/AntonioErdeljac/next13-ecommerce-admin/assets/57148990/98476334-0dea-4501-8b8a-bd8b3ea8be84">

while trying to log in or signup the clerk throws this above error.

**Comment by brogrammer-codes** [comment]
The free tier for clerk has likely reached the max number of users.

**Comment by AntonioErdeljac** [comment]
> The free tier for clerk has likely reached the max number of users.

Just FYI, Clerk has 5,000 users limit in its free tier, what is shown in the screenshot is the "development mode". Which is limited to 500 users
